"""Mutation-test `scripts/test_exec_reconcile.py`: the two-way execution check (Flex <-> ledgers).

Seeds real faults into a TEMP COPY of download_ib_records.py (via IB_RECORDS_MODULE; the real
script is never edited) and demands the suite catches every one. Engine: _mutate_records_core.py.

Run: python scripts/mutate_exec_reconcile.py
"""
from __future__ import annotations

import sys

from _mutate_records_core import run

MUTATIONS = [
    ('covered = lambda d: any(a <= d <= b for a, b in cover)',
     'covered = lambda d: True',
     'coverage ignored: not-yet-covered ids reported as missing'),
    ('covered = lambda d: any(a <= d <= b for a, b in cover)',
     'covered = lambda d: False',
     'coverage never true: ledger ids missing from Flex never reported'),
    ('                absent = []                            # the combo-level id (PROVISIONAL rule)\n',
     '                pass\n',
     'combo-level id rule removed (every VRP spread mis-reported)'),
    ('and legs_found == {leg["key"] for leg in fl["legs"]}):',
     'and True):',
     'combo rule too broad (a missing LEG passes as the combo id)'),
    ('elif abs(got[k] - q) > 1e-9:',
     'elif False:',
     'quantity never compared'),
    ('tol = max(0.005, 1e-4 * abs(fp))',
     'tol = 1e9',
     'price never compared (stock/future)'),
    ('sgn = -1.0 if _side(e) == "BUY" else 1.0',
     'sgn = 1.0',
     'spread net price sums both legs instead of sells - buys'),
    ('for e in execs) / q',
     'for e in execs) / 1.0',
     'multi-execution fill priced on the SUM, not the VWAP'),
    ('if contracts_w != contracts_g:',
     'if False:',
     'contract never compared'),
    ('if strat == "magic-formula" and e.get("assetCategory") == "CASH":',
     'if False:',
     'FX sweeps reported as unbooked (false alarm every day)'),
    ('        elif strat:\n',
     '        elif False:\n',
     'tagged executions treated as untagged'),
    ('how = ("assignment/exercise delivery" if codes & {"A", "Ex", "Ep"}',
     'how = ("assignment/exercise delivery" if codes & {"Ex", "Ep"}',
     'assignment deliveries not labelled'),
    ('e.get("dateTime", "")) < LINKED_FROM:',
     'e.get("dateTime", "")) < "00000000":',
     'pre-tagging executions reported'),
    ('                used.update(ids)\n',
     '',
     'tag-linked executions also reported as unbooked'),
    ('                if fl["sleeve"] == "options-vrp":\n',
     '                if False:\n',
     'VRP backfill file never written'),
    ('and any(_flex_key(e) == leg["key"] and _side(e) == leg["side"]\n                            for leg in fl["legs"])]',
     'and True]',
     'tag-only link ignores contract + side (grabs other spreads of the same run)'),
    ('warn = [f"two-way check incomplete: {s} ledger unavailable ({LEDGERS[s]})"\n            for s in missing_ledgers]',
     'warn = []',
     'a missing ledger is not reported'),
    ('"flex_tagged_unbooked", "flex_untagged",\n                "not_covered_aged")',
     '"flex_tagged_unbooked",\n                "not_covered_aged")',
     'untagged executions never alert'),
    ('        t = t.rsplit(".", 1)[0]                       # yfinance exchange suffix',
     '        pass                       # yfinance exchange suffix',
     'yfinance exchange suffix not stripped (European names never match)'),
    ('    return "BUY" if float(e.get("quantity") or 0) > 0 else "SELL"',
     '    return "SELL" if float(e.get("quantity") or 0) > 0 else "BUY"',
     'side from the quantity sign inverted (rows without buySell)'),
    ('                elif fl["date"] and _add_trading_days(fl["date"], AGEING_DAYS) < today:',
     '                elif False:',
     'uncovered ids never age into an alert'),
    ('AGEING_DAYS = 3 ',
     'AGEING_DAYS = 5 ',
     'ageing threshold loosened to 5 business days'),
    ('FAIL_CLASSES = ("field_mismatch", "ledger_not_in_flex", "flex_tagged_unbooked", "flex_untagged",\n                "not_covered_aged")',
     'FAIL_CLASSES = ("field_mismatch", "ledger_not_in_flex", "flex_tagged_unbooked", "flex_untagged")',
     'aged ids never alert'),
    ('            linked = codes & {"A", "Ex", "Ep"} and _assignment_for(e, date)',
     '            linked = ""',
     'assignment events never linked (alert on every assignment)'),
    ('                and abs(abs(float(e.get("quantity") or 0)) - a["shares"]) < 1e-9',
     '                and True',
     'delivery link ignores the quantity'),
    ('                and abs(float(e.get("tradePrice") or 0) - a["strike"]) < 0.01):',
     '                and True):',
     'delivery link ignores the price'),
    ('        if not (a["date"] and date <= a["date"] <= _add_trading_days(date, DELIVERY_WINDOW_DAYS)):',
     '        if not a["date"]:',
     'delivery link ignores the date window'),
    ('    if cids and len(cids) == len(legs):',
     '    if False:',
     'recorded conid ignored (spelling match again)'),
    ('        if abs(flex_comm - abs(float(fill["commission"]))) > 0.02:',
     '        if False:',
     'commission never compared'),
    ('    if fill.get("currency") and any(',
     '    if False and any(',
     'currency never compared'),
    ('        diffs.append(f"price: ledger {lp:g} vs Flex {fp:g}")\n    return diffs + extra',
     '        diffs.append(f"price: ledger {lp:g} vs Flex {fp:g}")\n    return diffs',
     'commission/currency differences dropped when the price agrees'),
    ('_conids(p, "entry_conid")',
     '[]',
     "magic-formula's recorded conid not read"),
    ('        except Exception:  # noqa: BLE001\n            missing.append(sleeve)',
     '        except KeyError:  # noqa: BLE001\n            missing.append(sleeve)',
     'an unreadable ledger crashes the job'),
    ('    if bs in ("BUY", "SELL"):\n        return bs\n',
     '    if bs in ("BUY", "SELL"):\n        return "SELL" if bs == "BUY" else "BUY"\n',
     'Flex side inverted'),
]

if __name__ == "__main__":
    sys.exit(run("test_exec_reconcile.py", MUTATIONS))
