"""Mutation-test `scripts/test_order_links.py`: the order -> IB record links (orderRef, execution ids, conid, commission, currency).

Seeds real faults into a TEMP COPY of the repo (the real files are never edited) and demands the
suite catches every one. Engine: _mutate_repo_core.py.

Run: python scripts/mutate_order_links.py
"""
from __future__ import annotations

import sys

from _mutate_repo_core import run

MUTATIONS = [
    ('paper/broker.py',
     '            order.orderRef = ref\n',
     '            pass\n',
     'broker never stamps orderRef on the order'),
    ('paper/broker.py',
     'ref = getattr(self, "order_ref", None)',
     'ref = self.order_ref',
     'a broker without a tag raises (a missing tag BLOCKS the trade)'),
    ('paper/broker.py',
     'while not getattr(trade, "fills", None) and waited < wait:',
     'while not getattr(trade, "fills", None) and waited < 0:',
     "no wait for execution details that trail 'Filled'"),
    ('paper/broker.py',
     'return [f.execution.execId for f in (getattr(trade, "fills", None) or [])]',
     'return []',
     'execution ids never collected'),
    ('paper/broker.py',
     '                        "exec_ids": ex, "order_ref": order.orderRef,\n                        **self._links(c, trade)}',
     '                        "exec_ids": [], "order_ref": order.orderRef,\n                        **self._links(c, trade)}',
     'a normal fill drops its execution ids'),
    ('paper/broker.py',
     '                        "exec_ids": ex, "order_ref": order.orderRef,\n                        **self._links(c, trade)}',
     '                        "exec_ids": ex, "order_ref": "",\n                        **self._links(c, trade)}',
     'a normal fill drops its orderRef'),
    ('paper/broker.py',
     '                            "exec_ids": ex, "order_ref": order.orderRef,\n                            **self._links(c, trade)}',
     '                            "exec_ids": [], "order_ref": order.orderRef,\n                            **self._links(c, trade)}',
     'a cancel-race fill drops its execution ids'),
    ('paper/broker.py',
     'order = self._tag(MarketOrder(action, qty))',
     'order = MarketOrder(action, qty)',
     'FX sweep orders go out untagged'),
    ('paper/broker.py',
     '"filled": float(amount_ccy), "exec_ids": ex}',
     '"filled": float(amount_ccy), "exec_ids": []}',
     'FX sweep drops its execution ids'),
    ('scripts/run_paper.py',
     '    b.order_ref = ORDER_REF\n',
     '',
     'RUNNER: make_broker never sets the tag'),
    ('scripts/run_paper.py',
     '    broker = make_broker(host=',
     '    broker = Broker(host=',
     'RUNNER: main() bypasses make_broker (untagged broker)'),
    ('scripts/run_paper.py',
     'ORDER_REF = f"magic-formula:{RUN_ID}"',
     'ORDER_REF = f"magic:{RUN_ID}"',
     'RUNNER: tag names the wrong strategy'),
    ('paper/orchestrator.py',
     'entry_order_ref=res.get("order_ref", ""),',
     'entry_order_ref="",',
     "orchestrator drops a BUY's orderRef"),
    ('paper/orchestrator.py',
     'entry_exec_ids=list(res.get("exec_ids") or []),',
     'entry_exec_ids=[],',
     "orchestrator drops a BUY's execution ids"),
    ('paper/orchestrator.py',
     '                                     order_ref=res.get("order_ref", ""),',
     '                                     order_ref="",',
     "orchestrator drops a SELL's orderRef"),
    ('paper/orchestrator.py',
     'exec_ids=res.get("exec_ids"),',
     'exec_ids=None,',
     "orchestrator drops a SELL's execution ids"),
    ('paper/state.py',
     '"entry_order_ref": pos.entry_order_ref, "entry_exec_ids": list(pos.entry_exec_ids),',
     '"entry_order_ref": "", "entry_exec_ids": [],',
     'closed trade loses the ENTRY links'),
    ('paper/state.py',
     '"exit_order_ref": order_ref, "exit_exec_ids": list(exec_ids or []),',
     '"exit_order_ref": order_ref, "exit_exec_ids": [],',
     'closed trade loses the EXIT execution ids'),
    ('paper/state.py',
     'entry_exec_ids: list[str] = field(default_factory=list)',
     'entry_exec_ids: list[str] = None',
     'positions saved before the fields existed load with None ids'),
    ('paper/state.py',
     'd["positions"] = [Position(**x) for x in d.get("positions", [])]',
     'd["positions"] = [Position(**{k: v for k, v in x.items() if "order_ref" not in k and "exec_ids" not in k}) for x in d.get("positions", [])]',
     'load() drops the links (save/load round trip)'),
    ('paper/broker.py',
     '                "commission": self._commission(trade),',
     '                "commission": None,',
     'commission never recorded'),
    ('paper/broker.py',
     '        return {"conid": int(getattr(contract, "conId", 0) or 0),',
     '        return {"conid": 0,',
     'conid never recorded'),
    ('paper/broker.py',
     '                if fills and all(r is not None and getattr(r, "execId", "") for r in reps):',
     '                if fills:',
     'commission reports counted before IB sent them'),
    ('paper/orchestrator.py',
     '                    entry_conid=int(res.get("conid") or 0),',
     '                    entry_conid=0,',
     "orchestrator drops a BUY's conid"),
    ('paper/orchestrator.py',
     '                    entry_commission=res.get("commission")))',
     '                    entry_commission=None))',
     "orchestrator drops a BUY's commission"),
    ('paper/orchestrator.py',
     '                                     commission=res.get("commission"))',
     '                                     commission=None)',
     "orchestrator drops a SELL's commission"),
    ('paper/state.py',
     '               "exit_commission": commission}',
     '               "exit_commission": None}',
     'closed trade loses the exit commission'),
]

if __name__ == "__main__":
    sys.exit(run("test_order_links.py", MUTATIONS))
